GET http://localhost:3030/getAuthors

####

POST http://localhost:3030/createAuthors
Content-Type: application/json

{
    "firstName": "Pippo",
    "lastName": "Paperino",
    "email": "Pippo@gmail.com",
    "dateOfBirth": "10 07 1990",
    "avatar": "non lo so"
}

####
GET http://localhost:3030/getAuthors/65f5d91490b59c657b02e9c2

####
PATCH http://localhost:3030/updateAuthor/65f5d91490b59c657b02e9c2
Content-Type: application/json

{
     "lastName": "Pluto"
}

####
DELETE http://localhost:3030/deleteAuthors/65f5d8fa90b59c657b02e9c0

####
GET http://localhost:3030/blogPosts

####
POST http://localhost:3030/blogPosts
Content-Type: application/json

{
    "category":"Nessuna categoria",
    "title":"Title 1",
    "cover":"cover 1",
    "readTime":{
        "value":130,
        "unit":"seconds"
    },
    "author":{
        "name":"Name author",
        "avatar":"Nessuno"
    },
    "content":"Empty",
    "comments":[]
        
    
    
}
####
GET http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b

####

PATCH http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b
Content-Type: application/json

{
    "content":"Full"
}

####
DELETE http://localhost:3030/blogPosts/65f5cd041e12a5814c3fb977

####
GET http://localhost:3030/exercise

####
GET http://localhost:3030/exercise/isActive

####
GET http://localhost:3030/exercise/26


####
GET http://localhost:3030/exercise/26e30

####
GET http://localhost:3030/exercise/brownblue

####
GET http://localhost:3030/exercise/green

####
GET http://localhost:3030/exercise/nogreen-noblue

####
GET http://localhost:3030/exercise/company

####
PATCH http://localhost:3030/updateAuthor/65f5d91490b59c657b02e9c2
Content-Type: application/json

{
     "avatar": "https://res.cloudinary.com/dp7v6spca/image/upload/v1711462324/PT043/rf2ovknsb0wasxgwk7n8.png"
}

####
PATCH http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b
Content-Type: application/json

{
    "cover":"https://res.cloudinary.com/dp7v6spca/image/upload/v1711462324/PT043/rf2ovknsb0wasxgwk7n8.png"
}

####
GET http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b/comments

####
POST http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b/comments
Content-Type: application/json

{
    "text":"Beautyfull"
    
}

####
GET http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b/comments/66042162bd7a7cc763451e0c

####
PATCH http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b/comments/66042350435ff1c9a4da1265
Content-Type: application/json

{
    "text": "very beautyfull"
}
####
DELETE http://localhost:3030/blogPosts/66042162bd7a7cc763451e0b/comments/660421afbd7a7cc763451e10